### ISSUE TITLE
Can not build in ruby 2.0.0

### ISSUE THREAD

**Issue by lazywei** [banister/binding_of_caller#18]
when i run `bundle install`, it failed

here is the error message

```
Installing binding_of_caller (0.6.8)
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /Users/lazywei/.rbenv/versions/2.0.0-p0/bin/ruby extconf.rb
creating Makefile

make
compiling binding_of_caller.c
binding_of_caller.c:4:10: fatal error: 'vm_core.h' file not found
#include "vm_core.h"
         ^
1 error generated.
make: *** [binding_of_caller.o] Error 1
```
